services:
  webserver:
    build: .
    restart: always
    ports:
      - "8787:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
    networks:
      - default

  database:
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_meconect
      MYSQL_USER: raiony
      MYSQL_PASSWORD: raiony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:
